// To run this code you need to install the following dependencies:
// npm install @google/genai mime
// npm install -D @types/node
// This code is generated by Google AI Studio, this was used to fetch and use the google gemini-2.0-flash model.
// https://aistudio.google.com/prompts/new_chat


import {
  GoogleGenAI,
} from '@google/genai';

async function main() {
  const ai = new GoogleGenAI({
    apiKey: process.env.REACT_APP_API_KEY,  
  });
  const config = {
    responseMimeType: 'text/plain',
  };
  const model = 'gemini-2.0-flash'; 
  const contents = [
    {
      role: 'user',
      parts: [
        {
          text: `Your input text here`,  
        },
      ],
    },
  ];

  const response = await ai.models.generateContentStream({
    model,
    config,
    contents,
  });
  let fileIndex = 0;
  for await (const chunk of response) {
    console.log(chunk.text);
  }
}

main();
